#<---------- `cloud` or `self-managed` ---------->
spring:
  profiles:
    active: cloud
#<---------- Execution in cloud environment ---------->
zeebe:
  client:
    cloud:
      region: dsm-1
      clusterId: caab18cc-488e-48f9-8ca5-864951ead365
      clientId: aqPhTk6PUZIZ2FTK2.-.9tK6IspbfGrA
      clientSecret: lTE8rtFzuX33CLJqLE~cnFGdgwCYn~ufQYgUDXcqZy21tkoiFn6qzH9E22x.D0Wu
#<---------- Execution in self-managed environment ---------->
    broker:
      gateway-address: 127.0.0.1:26500
#<---------- Logging ---------->
logging:
  level:
    root: info
    com:
      avg:
      kreditantrag:
        KreditantragApplication: debug
#<---------- Server ---------->
server:
  port: 7667
